version: $(ShortVersion).{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  VersionSuffix: rc1
  ShortVersion: 1.0.0
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: >-
    cd build

    .\build.ps1
artifacts:
- path: build\artifacts\*.nupkg
deploy: off