# to run from windows: set COMPOSE_CONVERT_WINDOWS_PATHS=1
#  to run elk: sudo sysctl -w vm.max_map_count=262144

#sudo mkdir -p /mnt/sda1/var/portainer/data
#sudo mkdir -p /mnt/sda1/logstash/
#sudo mkdir -p /mnt/sda1/data/elasticsearch/nodes
#docker cp logstash.conf elkbs_elk:/etc/logstash/conf.d

version: "3"

services:
#  visualizer:
#    image: "dockersamples/visualizer:stable"
#    ports:
#      - "8100:8080"
#    stop_grace_period: 1m30s
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    restart: always
#    container_name: visualiser
#    deploy:
#      replicas: 1
#      placement:
#        constraints: [node.role == manager]
#      resources:
#       limits:
#        cpus: '0.2'
#        memory: 100M
#    networks:
#     - bsnet

  portainer:
    image: "portainer/portainer"
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: "--templates http://templates/templates.json"
    networks:
      - bsnet
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/sda1/var/portainer/data:/data"

#  jenkins-ui:
#    image: "sstolbov/jenkins:1.1"
#    volumes:
#     - "/mnt/sda1/var/jenkins:/var/jenkins_home"
#     - "/var/run/docker.sock:/var/run/docker.sock"
#     - "/usr/local/bin/docker:/usr/bin/docker"
#    ports:
#     - "8000:8080"
##     - "50000:50000"
#    container_name: jenkins
#    restart: always
#    privileged: true
#    user: root
#    networks:
#     - bsnet
#    deploy:
#     replicas: 1
#     placement:
#      constraints: [node.role == manager]
#     resources:
#      limits:
#       cpus: '0.5'
#       memory: 400M

# networks:
#  app_net:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.18.0.0/24

  elk:
    #image: "sebp/elk"
    image: "sstolbov/elk"
    stop_grace_period: 1m30s
   # container_name: elk
    ports:
     - "5044:5044"
     - "9200:9200"
     - "5601:5601"
     - "5500:5500"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    #command: /opt/logstash/bin/logstash-plugin install logstash-output-email
    volumes:
      - "/mnt/sda1/logstash/:/etc/logstash/conf.d/"		
      - "/mnt/sda1/data/elasticsearch/nodes:/var/lib/elasticsearch/nodes"
    networks:
      - bsnet
    environment:
     - LOGSPOUT=ignore

#  logspout:
#    image: "gliderlabs/logspout:master"
#    deploy:
#      replicas: 1
#      placement:
#        constraints: [node.role == manager]
#    command: 'syslog://elkbs_elk:5000'
#    networks:
#      - bsnet
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    environment:
#     - DEBUG=true
#     - LOGSPOUT=ignore
#     - SYSLOG_FORMAT=rfc3164

 
networks:
    bsnet:
#          gateway: 172.18.0.1